name = "admin-menu-manager"
compatibility_date = "2026-06-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "thebar-preview"
database_id = "d852d5b8-a93e-4468-93f2-0083529bc68d"
migrations_dir = "db/migrations"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "thebar-preview"
database_id = "d852d5b8-a93e-4468-93f2-0083529bc68d"
migrations_dir = "db/migrations"

[[env.production.d1_databases]]
binding = "DB"
database_name = "thebar-production"
database_id = "407c68f2-a7c1-446d-8b9e-7b3be312bf4c"
migrations_dir = "db/migrations"
